namespace Ixen.Core.Accessibility
{
    public enum AccessibleRole
    {
        None,
        Group,
        Text,
        Heading,
        Image,
        Button,
        Link,
        CheckBox,
        RadioButton,
        Switch,
        TextField,
        Slider,
        ProgressBar,
        List,
        ListItem,
        Tree,
        TreeItem,
        Table,
        TableRow,
        TableCell,
        ColumnHeader,
        Tab,
        TabList,
        Menu,
        MenuItem,
        ComboBox,
        Dialog,
        ScrollBar,
        Presentation
    }
}
