<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="SkiaSharp" Version="4.151.1" />
		<PackageReference Include="SkiaSharp.Views" Version="4.151.1" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\Ixen.Core\Ixen.Core.csproj" />
	</ItemGroup>
</Project>